[package]
name = "rusty_os"
version = "0.1.0"
authors = ["Anthony Comstock <a32@pdx.edu>"]
edition = "2018"

[dependencies]
bootloader = "0.3.4"

[package.metadata.bootimage]
default-target = "x86_64-rusty_os.json"
